=== bartty/l2rambase/dist/gameserver/data/xml/xsd/DropListData.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element name="npc" maxOccurs="1" minOccurs="1">
					<xs:complexType>
						<xs:sequence maxOccurs="1" minOccurs="1">
							<xs:element name="droplist">
								<xs:complexType>
									<xs:sequence maxOccurs="50" minOccurs="1">
										<xs:element name="category">
											<xs:complexType>
												<xs:sequence maxOccurs="100" minOccurs="1">
													<xs:element name="item">
														<xs:complexType>
															<xs:attribute name="id" type="xs:positiveInteger" use="required" />
															<xs:attribute name="min" type="xs:positiveInteger" use="required" />
															<xs:attribute name="max" type="xs:positiveInteger" use="required" />
															<xs:attribute name="chance" type="xs:decimal" use="required" />
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="id" type="xs:positiveInteger" use="required" />
												<xs:attribute name="chance" type="xs:decimal" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element minOccurs="0" maxOccurs="unbounded" name="spoillist">
								<xs:complexType>
									<xs:sequence maxOccurs="5" minOccurs="1">
										<xs:element name="item" maxOccurs="100" minOccurs="1">
											<xs:complexType>
												<xs:attribute name="id" type="xs:positiveInteger" use="required" />
												<xs:attribute name="min" type="xs:positiveInteger" use="required" />
												<xs:attribute name="max" type="xs:positiveInteger" use="required" />
												<xs:attribute name="chance" type="xs:decimal" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="id" type="xs:positiveInteger" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== bartty/l2rambase/dist/gameserver/data/xml/stats/npc/droplist/20017.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/DropListData.xsd">
<!-- Воин Орков Вуку -->
<npc id="20017">
	<droplist>
		<category id="1" chance="70.000">
			<item id="57" min="122" max="197" chance="100.00000" />		<!-- Адена -->
		</category>
		<category id="2" chance="0.236">
			<item id="2" min="1" max="1" chance="2.98651" />		<!-- Длинный Меч -->
			<item id="120" min="1" max="1" chance="2.98651" />		<!-- Меч Отражения -->
			<item id="2012" min="1" max="1" chance="32.66485" />		<!-- Клинок Меча Отражения -->
			<item id="121" min="1" max="1" chance="2.98651" />		<!-- Меч Темной Воды -->
			<item id="415" min="1" max="1" chance="12.69036" />		<!-- Усиленные Мифрилом Набедренники -->
			<item id="416" min="1" max="1" chance="12.69036" />		<!-- Укрепленные Кожаные Набедренники -->
			<item id="186" min="1" max="1" chance="1.26904" />		<!-- Посох Магии -->
			<item id="1950" min="1" max="1" chance="31.72589" />		<!-- Заготовка Полулат -->
		</category>
		<category id="3" chance="15.176">
			<item id="34991" min="1" max="1" chance="24.42742" /> <!-- Обломок Доспеха -->
			<item id="34992" min="1" max="1" chance="31.71534" /> <!-- Драгоценные Аксессуары -->
			<item id="1817" min="1" max="1" chance="4.88550" />		<!-- Рецепт - Веревка -->
			<item id="5268" min="1" max="1" chance="0.97703" />		<!-- Рецепт - Суперкомпактная Упаковка: Заряды Души Ранг D (100%) -->
			<item id="1061" min="1" max="1" chance="32.55842" />		<!-- Большое Зелье Исцеления -->
			<item id="1878" min="1" max="1" chance="7.28792" />		<!-- Плетеный Лен -->
			<item id="1882" min="1" max="1" chance="4.94208" />		<!-- Кожа -->
			<item id="956" min="1" max="1" chance="0.49421" />		<!-- Свиток: Модифицировать Доспех (D) -->
		</category>
	</droplist>
	<spoillist>
			<item id="1897" min="1" max="1" chance="5.97620" />		<!-- Цепочка Ожерелья Мудрости -->
	</spoillist>
</npc>
</list>

=== bartty/l2rambase/dist/gameserver/data/xml/stats/npc/droplist/29006.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../xsd/DropListData.xsd">
<!-- Ядро -->
<npc id="29006">
	<droplist>
		<category id="1" chance="40">
			<item id="75" min="1" max="1" chance="12"/> <!-- Экскалибур -->
			<item id="84" min="1" max="1" chance="10"/> <!-- Меч Гомункула -->
			<item id="162" min="1" max="1" chance="12"/> <!-- Топор Войны -->
			<item id="174" min="1" max="1" chance="10"/> <!-- Топор Нирваны -->
			<item id="200" min="1" max="1" chance="10"/> <!-- Посох Мудреца -->
			<item id="233" min="1" max="1" chance="12"/> <!-- Кинжал Тьмы -->
			<item id="265" min="1" max="1" chance="10"/> <!-- Кастетные Клинки -->
			<item id="283" min="1" max="1" chance="12"/> <!-- Длинный Лук Аката -->
			<item id="301" min="1" max="1" chance="12"/> <!-- Скорпион -->
		</category>
		<category id="2" chance="60">
			<item id="60" min="1" max="1" chance="20"/> <!-- Композитный Доспех -->
			<item id="400" min="1" max="1" chance="20"/> <!-- Кожаный Доспех Тека -->
			<item id="420" min="1" max="1" chance="20"/> <!-- Кожаные Набедренники Тека -->
			<item id="441" min="1" max="1" chance="20"/> <!-- Туника Демона -->
			<item id="472" min="1" max="1" chance="20"/> <!-- Штаны Демона -->
		</category>
		<category id="3" chance="70">
			<item id="517" min="1" max="1" chance="20"/> <!-- Композитный Шлем -->
			<item id="2435" min="1" max="1" chance="20"/> <!-- Сапоги Демона -->
			<item id="2459" min="1" max="1" chance="20"/> <!-- Перчатки Демона -->
			<item id="107" min="1" max="1" chance="20"/> <!-- Композитный Щит -->
			<item id="951" min="1" max="1" chance="20"/> <!-- Свиток: Модифицировать Оружие (С) -->
		</category>
		<category id="4" chance="100">
			<item id="57" min="100000" max="150000" chance="100"/> <!-- Адена -->
		</category>
		<category id="5" chance="100">
			<item id="57" min="100000" max="150000" chance="100"/> <!-- Адена -->
		</category>
		<category id="6" chance="100">
			<item id="57" min="100000" max="150000" chance="100"/> <!-- Адена -->
		</category>
		<category id="7" chance="100">
			<item id="57" min="100000" max="150000" chance="100"/> <!-- Адена -->
		</category>
		<category id="8" chance="100">
			<item id="57" min="100000" max="150000" chance="100"/> <!-- Адена -->
		</category>
		<category id="9" chance="100">
			<item id="8744" min="2" max="4" chance="45"/> <!-- Камень Жизни Высокого Качества - Уровень 49 -->
			<item id="8745" min="2" max="4" chance="40"/> <!-- Камень Жизни Высокого Качества - Уровень 52 -->
			<item id="8754" min="1" max="2" chance="10"/> <!-- Камень Жизни Высшего Качества - Уровень 49 -->
			<item id="8755" min="1" max="2" chance="5"/> <!-- Камень Жизни Высшего Качества - Уровень 52 -->
		</category>
		<category id="10" chance="30">
			<item id="6662" min="1" max="1" chance="100"/> <!-- Кольцо Ядра -->
		</category>
	</droplist>
</npc>
</list>
