=== bartty/l2rambase/dist/gameserver/data/xml/stats/pets/pets.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT list (pet)*>

<!ELEMENT pet (stats|set|skills)*>
<!ATTLIST pet
	id CDATA #REQUIRED
	index CDATA #REQUIRED>
	
<!ELEMENT set (#PCDATA)>
<!ATTLIST set
	name CDATA #REQUIRED
	val CDATA #REQUIRED>

<!ELEMENT stats (stat)*>
<!ELEMENT stat (set)*>
<!ATTLIST stat
	level CDATA #REQUIRED>

<!ELEMENT skills (skill)*>
<!ELEMENT skill (#PCDATA)>
<!ATTLIST skill
	minLvl CDATA #REQUIRED
	skillId CDATA #REQUIRED
	skillLvl CDATA #REQUIRED>

=== bartty/l2rambase/dist/gameserver/data/xml/stats/pets/pet_16050.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE list SYSTEM "pets.dtd">
<list>
	<pet id="16050" index="30">
		<set name="sync_level" val="1" />
		<set name="load" val="54510" />
		<stats>
			<!--base stats-->
			<stat level="1">
				<set name="exp" val="0" />
				<set name="get_exp_type" val="100" />
				<set name="consume_meal_in_battle" val="10" />
				<set name="consume_meal_in_normal" val="10" />
				<set name="max_meal" val="18000" />
				<set name="soulshot_count" val="1" />
				<set name="spiritshot_count" val="1" />
				<set name="hp" val="68" />
				<set name="mp" val="20" />
				<set name="pdef" val="11" />
				<set name="mdef" val="8" />
				<set name="patk" val="1" />
				<set name="matk" val="1" />
				<set name="hpreg" val="2" />
				<set name="mpreg" val="1" />
			</stat>
			<!--base stats-->
			<stat level="2">
				<set name="exp" val="636" />
				<set name="get_exp_type" val="100" />
				<set name="consume_meal_in_battle" val="10" />
				<set name="consume_meal_in_normal" val="10" />
				<set name="max_meal" val="18000" />
				<set name="soulshot_count" val="1" />
				<set name="spiritshot_count" val="1" />
				<set name="hp" val="83" />
				<set name="mp" val="24" />
				<set name="pdef" val="12" />
				<set name="mdef" val="8" />
				<set name="patk" val="1" />
				<set name="matk" val="1" />
				<set name="hpreg" val="2" />
				<set name="mpreg" val="1" />
			</stat>
			<!--base stats-->
			<stat level="3">
				<set name="exp" val="798" />
				<set name="get_exp_type" val="100" />
				<set name="consume_meal_in_battle" val="10" />
				<set name="consume_meal_in_normal" val="10" />
				<set name="max_meal" val="18000" />
				<set name="soulshot_count" val="1" />
				<set name="spiritshot_count" val="1" />
				<set name="hp" val="99" />
				<set name="mp" val="27" />
				<set name="pdef" val="12" />
				<set name="mdef" val="9" />
				<set name="patk" val="1" />
				<set name="matk" val="1" />
				<set name="hpreg" val="2" />
				<set name="mpreg" val="1" />
			</stat>
			<!--base stats-->
			<stat level="4">
				<set name="exp" val="1236" />
				<set name="get_exp_type" val="100" />
				<set name="consume_meal_in_battle" val="10" />
				<set name="consume_meal_in_normal" val="10" />
				<set name="max_meal" val="18000" />
				<set name="soulshot_count" val="1" />
				<set name="spiritshot_count" val="1" />
				<set name="hp" val="117" />
				<set name="mp" val="31" />
				<set name="pdef" val="12" />
				<set name="mdef" val="9" />
				<set name="patk" val="1" />
				<set name="matk" val="1" />
				<set name="hpreg" val="2" />
				<set name="mpreg" val="1" />
			</stat>
			<!--base stats-->
			<stat level="5">
				<set name="exp" val="2158" />
				<set name="get_exp_type" val="100" />
				<set name="consume_meal_in_battle" val="10" />
				<set name="consume_meal_in_normal" val="10" />
				<set name="max_meal" val="18000" />
				<set name="soulshot_count" val="1" />
				<set name="spiritshot_count" val="1" />
				<set name="hp" val="138" />
				<set name="mp" val="35" />
				<set name="pdef" val="13" />
				<set name="mdef" val="9" />
				<set name="patk" val="1" />
				<set name="matk" val="1" />
				<set name="hpreg" val="2" />
				<set name="mpreg" val="1" />
			</stat>
			<!--base stats-->
			<stat level="6">
				<set name="exp" val="3836" />
				<set name="get_exp_type" val="100" />
				<set name="consume_meal_in_battle" val="10" />
				<set name="consume_meal_in_normal" val="10" />
				<set name="max_meal" val="18000" />
				<set name="soulshot_count" val="1" />
				<set name="spiritshot_count" val="1" />
				<set name="hp" val="161" />
				<set name="mp" val="39" />
				<set name="pdef" val="13" />
				<set name="mdef" val="10" />
				<set name="patk" val="1" />
				<set name="matk" val="1" />
				<set name="hpreg" val="2" />
				<set name="mpreg" val="1" />
			</stat>
			<!--base stats-->
			<stat level="7">
				<set name="exp" val="6598" />
				<set name="get_exp_type" val="100" />
				<set name="consume_meal_in_battle" val="10" />
				<set name="consume_meal_in_normal" val="10" />
				<set name="max_meal" val="18000" />
				<set name="soulshot_count" val="1" />
				<set name="spiritshot_count" val="1" />
				<set name="hp" val="186" />
				<set name="mp" val="42" />
				<set name="pdef" val="14" />
				<set name="mdef" val="10" />
				<set name="patk" val="1" />
				<set name="matk" val="1" />
				<set name="hpreg" val="2" />
				<set name="mpreg" val="1" />
			</stat>
			<!--base stats-->
			<stat level="8">
				<set name="exp" val="10836" />
				<set name="get_exp_type" val="100" />
				<set name="consume_meal_in_battle" val="10" />
				<set name="consume_meal_in_normal" val="10" />
				<set name="max_meal" val="18000" />
				<set name="soulshot_count" val="1" />
				<set name="spiritshot_count" val="1" />
				<set name="hp" val="215" />
				<set name="mp" val="46" />
				<set name="pdef" val="14" />
				<set name="mdef" val="11" />
				<set name="patk" val="1" />
				<set name="matk" val="1" />
				<set name="hpreg" val="2" />
				<set name="mpreg" val="1" />
			</stat>
			<!--base stats-->
			<stat level="9">
				<set name="exp" val="16998" />
				<set name="get_exp_type" val="100" />
				<set name="consume_meal_in_battle" val="10" />
				<set name="consume_meal_in_normal" val="10" />
				<set name="max_meal" val="18000" />
				<set name="soulshot_count" val="1" />
				<set name="spiritshot_count" val="1" />
				<set name="hp" val="246" />
				<set name="mp" val="50" />
				<set name="pdef" val="15" />
				<set name="mdef" val="11" />
				<set name="patk" val="1" />
				<set name="matk" val="1" />
				<set name="hpreg" val="2" />
				<set name="mpreg" val="1" />
			</stat>
			<!--base stats-->
			<stat level="10">
				<set name="exp" val="25596" />
				<set name="get_exp_type" val="100" />
				<set name="consume_meal_in_battle" val="10" />
				<set name="consume_meal_in_normal" val="10" />
				<set name="max_meal" val="18000" />
				<set name="soulshot_count" val="1" />
				<set name="spiritshot_count" val="1" />
				<set name="hp" val="280" />
				<set name="mp" val="54" />
				<set name="pdef" val="15" />
				<set name="mdef" val="11" />
				<set name="patk" val="1" />
				<set name="matk" val="1" />
				<set name="hpreg" val="2" />
				<set name="mpreg" val="1" />
			</stat>
			<!--base stats-->
			<stat level="11">
				<set name="exp" val="37198" />
				<set name="get_exp_type" val="100" />
				<set name="consume_meal_in_battle" val="10" />
				<set name="consume_meal_in_normal" val="10" />
				<set name="max_meal" val="18000" />
				<set name="soulshot_count" val="1" />
				<set name="spiritshot_count" val="1" />
				<set name="hp" val="318" />
				<set name="mp" val="58" />
				<set name="pdef" val="16" />
				<set name="mdef" val="12" />
				<set name="patk" val="1" />
				<set name="matk" val="1" />
				<set name="hpreg" val="3" />
				<set name="mpreg" val="1" />
			</stat>
			<!--base stats-->
			<stat level="12">
				<set name="exp" val="52436" />
				<set name="get_exp_type" val="100" />
				<set name="consume_meal_in_battle" val="10" />
				<set name="consume_meal_in_normal" val="10" />
				<set name="max_meal" val="18000" />
				<set name="soulshot_count" val="1" />
				<set name="spiritshot_count" val="1" />
				<set name="hp" val="343" />
				<set name="mp" val="62" />
				<set name="pdef" val="17" />
				<set name="mdef" val="12" />
				<set name="patk" val="1" />
				<set name="matk" val="1" />
				<set name="hpreg" val="3" />
				<set name="mpreg" val="1" />
			</stat>
			<!--base stats-->
			<stat level="13">
				<set name="exp" val="71998" />
				<set name="get_exp_type" val="100" />
				<set name="consume_meal_in_battle" val="10" />
				<set name="consume_meal_in_normal" val="10" />
				<set name="max_meal" val="18000" />
				<set name="soulshot_count" val="1" />
				<set name="spiritshot_count" val="1" />
				<set name="hp" val="369" />
				<set name="mp" val="66" />
				<set name="pdef" val="17" />
				<set name="mdef" val="13" />
				<set name="patk" val="1" />
				<set name="matk" val="1" />
				<set name="hpreg" val="3" />
				<set name="mpreg" val="1" />
			</stat>
			<!--base stats-->
			<stat level="14">
				<set name="exp" val="96636" />
				<set name="get_exp_type" val="100" />
				<set name="consume_meal_in_battle" val="10" />
				<set name="consume_meal_in_normal" val="10" />
				<set name="max_meal" val="18000" />
				<set name="soulshot_count" val="1" />
				<set name="spiritshot_count" val="1" />
				<set name="hp" val="396" />
				<set name="mp" val="70" />
				<set name="pdef" val="18" />
				<set name="mdef" val="13" />
				<set name="patk" val="1" />
				<set name="matk" val="1" />
				<set name="hpreg" val="3" />
				<set name="mpreg" val="1" />
			</stat>
			<!--base stats-->
			<stat level="15">
				<set name="exp" val="127158" />
				<set name="get_exp_type" val="100" />
				<set name="consume_meal_in_battle" val="10" />
				<set name="consume_meal_in_normal" val="10" />
				<set name="max_meal" val="18000" />
				<set name="soulshot_count" val="1" />
				<set name="spiritshot_count" val="1" />
				<set name="hp" val="424" />
				<set name="mp" val="75" />
				<set name="pdef" val="27" />
				<set name="mdef" val="13" />
				<set name="patk" val="1" />
				<set name="matk" val="1" />
				<set name="hpreg" val="3" />
				<set name="mpreg" val="1" />
			</stat>
			<!--base stats-->
			<stat level="16">
				<set name="exp" val="164436" />
				<set name="get_exp_type" val="100" />
				<set name="consume_meal_in_battle" val="10" />
				<set name="consume_meal_in_normal" val="10" />
				<set name="max_meal" val="18000" />
